#!/usr/bin/env bash
alias e="\$EDITOR"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

#alias git=hub
alias gc="git checkout"
alias gcb="git checkout -"
alias gad="git add"
alias gcm="git commit"
alias gpl="git pull"
alias gp="git push"
alias gpf="git push -f"
alias c="bat"
alias clip="xclip -selection clipboard"
alias unclip="xclip -selection clipboard -o"
alias open="xdg-open"
alias pip="pip3"
