#!/usr/bin/env bash

alias e="\$EDITOR"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

#alias git=hub
alias gc="git checkout "
alias gcb="git checkout -"
alias gcm="git commit "
alias gp="git push"
alias gpf="git push -f"
alias gpu ="git push -u origin "
alias c="bat"
alias clip="xclip -selection clipboard"
alias unclip="xclip -selection clipboard -o"

