#!/usr/bin/env bash
alias e="\$EDITOR"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

#alias git=hub
alias gc="git checkout"
alias gcb="git checkout -"
alias gad="git add"
alias gcm="git commit"
alias gpl="git pull"
alias gp="git push"
alias gpf="git push -f"
alias ghome="cd ~/"
alias c="bat"
alias clip="xclip -selection clipboard"
alias unclip="xclip -selection clipboard -o"
alias open="xdg-open"
alias pip="pip3"
alias gow="cd /mnt/c/Users/AntonGarriFagerbakk"
alias sshDBTest="ssh ubuntu@ns3190242.ip-5-39-74.eu"
alias sshAppTest="ssh ubuntu@ns3134110.ip-51-38-181.eu"
