# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.

export ZSH="$HOME/.oh-my-zsh"
export GKE_PROJECT="regal-stack-339412"
ZSH_THEME="powerlevel10k/powerlevel10k"

CASE_SENSITIVE="false"

HYPHEN_INSENSITIVE="false"
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"

alias python="python3"

plugins=(
  git
  sudo
  httpie
  extract
  encode64
  command-not-found
  github
  node
  pip
  python
  sudo
  vscode
)

lazy_touch()
{
  touch $1
 xdg-open $1
}

export PATH=$PATH:"/mnt/c/Users/AntonGarriFagerbakk/AppData/Local/Programs/Microsoft VS Code/bin"
export PATH=$PATH:"/home/agfagerbakk/chromedriver_linux64/chromedriver"

source $ZSH/oh-my-zsh.sh
source ~/.shell_env

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
ghome

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/agfagerbakk/google-cloud-sdk/path.zsh.inc' ]; then . '/home/agfagerbakk/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/agfagerbakk/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/agfagerbakk/google-cloud-sdk/completion.zsh.inc'; fi
