# Path to your oh-my-zsh installation.

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

CASE_SENSITIVE="false"

HYPHEN_INSENSITIVE="false"
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"

plugins=(
  git
  sudo
  httpie
  extract
  encode64
  command-not-found
  github
  node
  npm
  pip
  python
  sudo
  vscode
)

lazy_touch()
{
  touch $1
 xdg-open $1
}

source $ZSH/oh-my-zsh.sh
source ~/.shell_env
