# Path to your oh-my-zsh installation.

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

CASE_SENSITIVE="false"

HYPHEN_INSENSITIVE="false"
PROMPT_EOL_MARK=
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"
BROWSER="vivaldi-stable"

plugins=(
  git
  sudo
  httpie
  extract
  encode64
  command-not-found
  github
  last-working-dir
  node
  npm
  per-directory-history
  pip
  python
  sudo
  vscode  
)

lazy_touch()
{
  touch $1
 xdg-open $1
}

source $ZSH/oh-my-zsh.sh
source ~/.shell_env
